// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID               string             `json:"id"`
	MemberCardNumber *string            `json:"member_card_number"`
	TotalPrice       string             `json:"total_price"`
	DiscountAmount   string             `json:"discount_amount"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type OrderItem struct {
	ID        string `json:"id"`
	OrderID   string `json:"order_id"`
	ProductID string `json:"product_id"`
	Quantity  int32  `json:"quantity"`
	UnitPrice string `json:"unit_price"`
}

type Product struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Price       string             `json:"price"`
	IsLimited   bool               `json:"is_limited"`
	LastOrderAt pgtype.Timestamptz `json:"last_order_at"`
}
