/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Food Store API
 * Point-of-sale API for browsing products and placing orders.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrderProductItem } from './createOrderProductItem';

export interface CreateOrderResponse {
  order_id?: string;
  total_price?: string;
  discount_amount?: string;
  products?: CreateOrderProductItem[];
}
