/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Food Store API
 * Point-of-sale API for browsing products and placing orders.
 * OpenAPI spec version: 1.0.0
 */
import type { CreateOrderItemRequest } from './createOrderItemRequest';

export interface CreateOrderRequest {
  member_card_number?: string;
  /** @minItems 1 */
  items: CreateOrderItemRequest[];
}
