/**
 * Generated by orval 🍺
 * Do not edit manually.
 * Food Store API
 * Point-of-sale API for browsing products and placing orders.
 * OpenAPI spec version: 1.0.0
 */

export interface ErrorResponse {
  code?: number;
  msg?: string;
}
